// Code generated by Microsoft (R) TypeSpec Code Generator.

package todo.todoitems;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.serialization.json.JsonReader;
import io.clientcore.core.serialization.json.JsonSerializable;
import io.clientcore.core.serialization.json.JsonToken;
import io.clientcore.core.serialization.json.JsonWriter;
import java.io.IOException;
import java.util.List;
import todo.TodoAttachment;

/**
 * The TodoAttachmentList model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class TodoAttachmentList implements JsonSerializable<TodoAttachmentList> {
    /*
     * The items property.
     */
    @Metadata(generated = true)
    private final List<TodoAttachment> items;

    /**
     * Creates an instance of TodoAttachmentList class.
     * 
     * @param items the items value to set.
     */
    @Metadata(generated = true)
    private TodoAttachmentList(List<TodoAttachment> items) {
        this.items = items;
    }

    /**
     * Get the items property: The items property.
     * 
     * @return the items value.
     */
    @Metadata(generated = true)
    public List<TodoAttachment> getItems() {
        return this.items;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("items", this.items, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of TodoAttachmentList from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of TodoAttachmentList if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the TodoAttachmentList.
     */
    @Metadata(generated = true)
    public static TodoAttachmentList fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<TodoAttachment> items = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("items".equals(fieldName)) {
                    items = reader.readArray(reader1 -> TodoAttachment.fromJson(reader1));
                } else {
                    reader.skipChildren();
                }
            }
            return new TodoAttachmentList(items);
        });
    }
}
