emit:
 - "@typespec/openapi3"
 - "@typespec/http-server-csharp"
 - "@typespec/http-client-csharp"
 - "@typespec/http-client-java"
 - "@azure-tools/typespec-ts"
#  - "@typespec/http-server-javascript" # js server gen throws error: Error: Unimplemented: new form of multipart requests
 - "@typespec/http-client-python"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../openapi3"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{project-root}/../clients/dotnet"
  "@typespec/http-server-csharp":
    emitter-output-dir: "{project-root}/../servers/aspnet/generated"  
  # "@typespec/http-server-javascript":
  #   emitter-output-dir: "{project-root}/../servers/node/tsp-output/@typespec/http-server-javascript"
  #   express: true
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/../clients/java"
  "@azure-tools/typespec-ts":
    isModularLibrary: true
    generateMetadata: true
    azureSdkForJs: false
    generateSample: true
    "emitter-output-dir": "{project-root}/../clients/javascript"
    packageDetails:
      name: "@notabrand/todo-non-branded"
  "@typespec/http-client-python":
    emitter-output-dir: "{project-root}/../clients/python"
